// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService 暴露单聊能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Conversations 返回会话列表（按最近消息时间倒序）。
 * 
 * 目前直接从节点目录 + 消息推导，避免为 UI 单独维护一张表。
 */
export function Conversations(): $CancellablePromise<$models.ConversationDTO[] | null> {
    return $Call.ByID(1845362008);
}

/**
 * History 返回与某对端的最近消息（新→旧）。
 */
export function History(peerID: string, limit: number, before: number): $CancellablePromise<$models.MessageDTO[] | null> {
    return $Call.ByID(4168301964, peerID, limit, before);
}

/**
 * SendMessage 发送单聊消息，返回已入库的消息（状态为 pending，等待 ACK）。
 */
export function SendMessage(peerID: string, text: string): $CancellablePromise<$models.MessageDTO> {
    return $Call.ByID(2543576585, peerID, text);
}
