// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GroupService 暴露群聊能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddMember 由群主添加成员（epoch+1 并广播）。
 */
export function AddMember(groupID: string, memberID: string): $CancellablePromise<$models.GroupDTO> {
    return $Call.ByID(715349740, groupID, memberID);
}

/**
 * Create 建群（本方为群主，上限 20 人）。
 */
export function Create(name: string, memberIDs: string[] | null): $CancellablePromise<$models.GroupDTO> {
    return $Call.ByID(3621918031, name, memberIDs);
}

/**
 * History 返回群历史消息（新→旧）。
 */
export function History(groupID: string, limit: number, before: number): $CancellablePromise<$models.MessageDTO[] | null> {
    return $Call.ByID(737406809, groupID, limit, before);
}

/**
 * List 返回本机已知群。
 */
export function List(): $CancellablePromise<$models.GroupDTO[] | null> {
    return $Call.ByID(3653608303);
}

/**
 * SendImage 群发一张本地图片（与单聊同一套压缩与内联格式）。
 */
export function SendImage(groupID: string, path: string): $CancellablePromise<$models.MessageDTO> {
    return $Call.ByID(540331366, groupID, path);
}

/**
 * SendImageBytes 群发剪贴板里的图片（dataB64 为 base64 字符串）。
 */
export function SendImageBytes(groupID: string, name: string, dataB64: string): $CancellablePromise<$models.MessageDTO> {
    return $Call.ByID(3905079725, groupID, name, dataB64);
}

/**
 * SendMessage 群发消息（扇出到在线成员；离线成员不暂存）。
 */
export function SendMessage(groupID: string, text: string): $CancellablePromise<$models.MessageDTO> {
    return $Call.ByID(612926024, groupID, text);
}
