// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConversationDTO 是会话列表项。
 */
export interface ConversationDTO {
    "convId": string;
    "kind": string;
    "title": string;
    "peerId"?: string;
    "state"?: string;
    "isOnline": boolean;
    "lastTime": number;
}

/**
 * DiagnosticsDTO 是诊断面板数据。
 */
export interface DiagnosticsDTO {
    "peersTotal": number;
    "peersOnline": number;
    "activeSessions": number;
    "activeTransfers": number;
    "seedCount": number;
    "seedDetails": SeedDTO[] | null;
    "interfaceSummary": string[] | null;
}

/**
 * GroupDTO 是群项。
 */
export interface GroupDTO {
    "groupId": string;
    "name": string;
    "ownerId": string;
    "epoch": number;
    "isOwner": boolean;
    "members": GroupMemberDTO[] | null;
    "createdAt": number;
}

/**
 * GroupMemberDTO 是群成员项。
 */
export interface GroupMemberDTO {
    "nodeId": string;
    "displayName": string;
    "role": string;
    "state": string;
}

/**
 * MessageDTO 是消息的对外表示。
 */
export interface MessageDTO {
    "msgId": string;
    "convId": string;
    "senderId": string;
    "direction": string;
    "content": string;
    "msgType": string;
    "fileId"?: string;
    "state": string;
    "sentAt": number;
    "recvAt"?: number;
}

/**
 * PeerDTO 是节点列表项。
 * 
 * 注意：UI 必须同时展示「节点在线」（announce 维护）与「连接可用」（TCP 维护），
 * 否则用户会看到「在线但发不出消息」而困惑（ADR-009 的代价之一）。
 */
export interface PeerDTO {
    "nodeId": string;
    "shortId": string;
    "displayName": string;
    "state": string;
    "lastAddr": string;
    "subnet": string;
    "source": string;
    "lastSeen": number;
    "online": boolean;
    "connected": boolean;
}

/**
 * SeedDTO 是种子状态项（含退避信息）。
 */
export interface SeedDTO {
    "addr": string;
    "failCount": number;
    "nodeId": string;
    "tcpPort": number;
    "subnet": string;
}

/**
 * SelfCheckDTO 是部署前置条件（P-1 / P-2）自检结果。
 * 
 * Detail 字段是【给人读的结论】而不是错误码：这两条前提只有部署者能修
 * （改网段规划 / 开三层路由），软件侧无能为力，因此必须说清「怎么修」。
 */
export interface SelfCheckDTO {
    "performed": boolean;
    "seedCount": number;
    "learned": number;
    "p1OK": boolean;
    "p1Detail": string;
    "p2Overlap": boolean;
    "p2Detail": string;
    "seeds": SeedDTO[] | null;
}

/**
 * SelfDTO 是本机身份。
 */
export interface SelfDTO {
    "nodeId": string;
    "displayName": string;
    "tcpPort": number;
    "udpPort": number;
    "subnet": string;
}

/**
 * SettingsDTO 是设置项。
 */
export interface SettingsDTO {
    "displayName": string;
    "downloadDir": string;
    "autoOpen": boolean;
    "tcpPort": number;
    "udpPort": number;
    "interfaceMode": string;
    "allowInterfaces": string[] | null;
    "denyInterfaces": string[] | null;
    "seeds": string[] | null;
    "seedRefreshSec": number;
    "seedsPerRefresh": number;
    "maxConcurrent": number;
    "chunkSize": number;
    "windowSize": number;
    "maxActiveConns": number;
    "idleTimeoutSec": number;
    "requireAuth": boolean;
    "encryption": string;
}

/**
 * TransferDTO 是传输任务项。
 */
export interface TransferDTO {
    "jobId": string;
    "peerId": string;
    "fileName": string;
    "fileSize": number;
    "direction": string;
    "localPath": string;
    "completed": number;
    "totalChunks": number;
    "percent": number;
    "status": string;
    "error"?: string;
    "updatedAt": number;
}
