// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PeerService 暴露节点目录与诊断信息。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Diagnostics 返回诊断面板数据。
 * 
 * 「常驻连接数」与「无保活流量」是 ADR-009 的两条可观测断言，
 * 因此它们必须出现在诊断面板上，而不是只存在于日志里。
 */
export function Diagnostics(): $CancellablePromise<$models.DiagnosticsDTO> {
    return $Call.ByID(733396974);
}

/**
 * List 返回节点列表。
 */
export function List(): $CancellablePromise<$models.PeerDTO[] | null> {
    return $Call.ByID(4022756370);
}

/**
 * Self 返回本机身份与运行参数。
 */
export function Self(): $CancellablePromise<$models.SelfDTO> {
    return $Call.ByID(257045392);
}
