// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService 读写配置。
 * 
 * 重要：端口与网卡相关项【需重启生效】；前端必须明确标注，
 * 否则用户改完端口发现没变化会认为是 bug（架构书 7.4）。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DownloadDir 返回当前接收目录。
 */
export function DownloadDir(): $CancellablePromise<string> {
    return $Call.ByID(3031120382);
}

/**
 * Get 返回当前配置快照。
 */
export function Get(): $CancellablePromise<$models.SettingsDTO> {
    return $Call.ByID(4032185989);
}

/**
 * ListInterfaces 返回本机参与发现的网卡摘要（供设置页展示）。
 */
export function ListInterfaces(): $CancellablePromise<string[] | null> {
    return $Call.ByID(648205731);
}

/**
 * Save 落盘配置。返回需要重启才能生效的项清单。
 */
export function Save($in: $models.SettingsDTO): $CancellablePromise<string[] | null> {
    return $Call.ByID(3816168166, $in);
}
