// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TransferService 暴露文件传输能力。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get 返回单个传输任务。
 */
export function Get(jobID: string): $CancellablePromise<$models.TransferDTO> {
    return $Call.ByID(948894351, jobID);
}

/**
 * List 返回全部（含已结束的）传输任务。
 */
export function List(): $CancellablePromise<$models.TransferDTO[] | null> {
    return $Call.ByID(3831912297);
}

/**
 * SendFile 发送文件（异步：立即返回 job_id，进度通过事件推送）。
 */
export function SendFile(peerID: string, path: string): $CancellablePromise<string> {
    return $Call.ByID(3239939129, peerID, path);
}
